### ISSUE TITLE
Display query grid: No titles in tabs of second row

### ISSUE THREAD

**Issue by svades** [camptocamp/ngeo#3273] opened 2017-12-14 09:57 UTC
Project:
* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2.1

Steps to reproduce the issue:
* do a query over a surface
* open a tab in the second row
* the titles of the tabs in the second row are broken

Result:
![display_query_grid](https://user-images.githubusercontent.com/22655359/33985985-7a0baa4e-e0bc-11e7-807b-f8627d989bf0.PNG)

As soon as there are two rows of tabs in the display query grid the titles are broken.

**Comment by sbrunner** [comment] 2017-12-20 15:12
see: https://github.com/elboletaire/tabbedcontent/issues/19

**Comment by ger-benjamin** [comment] 2017-12-21 08:05
@svades I can't reproduce this issue (I've 2 lines of tabs with a normal style. But I've lesser tabs). Which browser (and version) do you use, and on which OS ?

**Comment by svades** [comment] 2017-12-21 08:31
It usually happens at the eleventh, twelfth, thirteenth... tab.
I use IE11 (Version 11.0.9600.18860) and I could also reproduce it in Chrome (Version 63.0.3239.108)  and Firefox ESR (52.4.1) on Windows 7 Enterprise.

**Comment by ybolognini** [comment] 2018-01-08 10:33
@llienher Please check with more than 10 tabs

**Comment by llienher** [comment] 2018-01-10 10:52
@svades We merged a fix for an issue related to merged tabs for 2.2.2 minor release. We saw that when a merged tabs is defined with a name containing space, brackets, parenthenses, etc, the grid headers would break because the html would use the name defined in the controller as element id. This way the CSS selector was broken in the javascript as it was trying to retrieve several ids (from the spaces), not just the one element we wanted to 'reflow' the grid at tab selection.

Our fix should not affect any project setup as the controller setup (mergeTabs) will be the same as now. But the issue is not related to having more than 10 tabs, while the consequences where similar to what you described.

Please reopen this issue if it's there is some remaining issue when you are able to test 2.2.2 in your project.

**Comment by svades** [comment] 2018-01-29 10:37
I could now test in in gmf 2.2.2 and there is an error doing a request over a surface:
![typeerror_request](https://user-images.githubusercontent.com/22655359/35506076-6ed906da-04e8-11e8-9351-a5d4d52d73f8.PNG)

The displayQueryGrid remains empty:
![empty_grid](https://user-images.githubusercontent.com/22655359/35506158-abb6036e-04e8-11e8-95fe-b19d64f3308f.PNG)

**Comment by llienher** [comment] 2018-01-29 11:12
Thanks for you feedback, I'm reopening this issue. I'm still not sure if it is related the the initial fix we addressed here.

Do you have an instance where I can see this issue more in detail ?

**Comment by svades** [comment] 2018-01-29 11:59
Our branch "gmf222" is where we updated the master to gmf 2.2.2.
Unfortunately, the URL (map.geo.dev.bs.ch/ngeodesktop) is not reachable for you because it is on our development environment.

**Comment by jwkaltz** [comment] 2018-01-29 15:06
Hi Silvana, we checked this functionality on our demo project; the default demo project does not use the displayquerygrid, but we built a test instance 2.2.2 with Laurent that does activate the displayquerygrid: https://gmf-test.sig.cloud.camptocamp.net/llienher
The query works fine, there. We suspect that the JavaScript error you mention comes from a Baselstadt specific adaptation. Can you please verify that, and, if needed, open a support ticket?

**Closed by jwkaltz** 2018-01-29 15:06 UTC
Labels: Ongoing

**Comment by svades** [comment] 2018-01-30 06:50
Hi,
I could reproduce the issue on your demo project.
I loaded all the layers in the theme "Demo" and did a request over a big surface. Then the displayquerygrid appears but is white and empty (see screenshot).
![demo_empty_querygrid](https://user-images.githubusercontent.com/22655359/35551997-262d1a8e-0592-11e8-8be2-da84d5b885cc.PNG)

**Comment by llienher** [comment] 2018-01-30 07:49
Hi,

I have been able to narrow the issue to the 'two layers' in the demo (not my own test instance, it's not reliable) layer and precisely break the grid...
I'm going to open a new issue to this problem.

**Comment by llienher** [comment] 2018-01-30 07:56
New issue opened here:
https://github.com/camptocamp/ngeo/issues/3462
