### ISSUE TITLE
ngeo mobile does not work on several mobile devices

### ISSUE THREAD

**Issue by gnerred** [camptocamp/ngeo#2214] opened 2017-01-18 07:18 UTC
Version 2.1.0rc7

I have tested https://preprod.cartoriviera.ch/v2 on several mobile devices, and it doesn't work with the following, especially on iOS devices (not exhaustive).... 

Default browser on galaxy note 8'' Android 4.4.2 (physical device)
![image](https://cloud.githubusercontent.com/assets/1989467/22054015/0497cc50-dd54-11e6-8c9d-b6e1f77de025.png)

Safari on iPhone 7 iOS 10.0 (Browserstack, touch on buttons has no effect) : 
![image](https://cloud.githubusercontent.com/assets/1989467/22054065/435ad23e-dd54-11e6-9010-0aa5d40b2e5a.png)

Safari on iPhone 5 iOS 6 (Browserstack) : 
![image](https://cloud.githubusercontent.com/assets/1989467/22054202/9f4ba7b2-dd54-11e6-8eda-06f7d2abebdb.png)

Safari on iPhone 6S iOS 9 (Browserstack, touch on buttons has no effect) : 
![image](https://cloud.githubusercontent.com/assets/1989467/22054267/0074d0b8-dd55-11e6-95b2-f34a23cd7d2b.png)

**Comment by ger-benjamin** [comment] 2017-01-18 12:58
I can reproduce with our demo but not on our real devices...

**Comment by gnerred** [comment] 2017-01-18 13:09
I have reproduced the problem on my real Galaxy note 8'' (Android 4.4.2) with your demo : 
![image](https://cloud.githubusercontent.com/assets/1989467/22065238/a69f0c10-dd87-11e6-890e-c35ea6a7372e.png)

**Comment by sbrunner** [comment] 2017-01-20 15:48
@gnerred witch browser and browser version do you have?

**Comment by gnerred** [comment] 2017-01-23 06:26
As said in my first message, I'm using default browser (Android browser) on galaxy note 8'' Android 4.4.2.

**Comment by ybolognini** [comment] 2017-01-23 09:47
@gnerred 
As for the Galaxy Note problem, our supported devices/browsers list includes browser Chrome for Android devices. This list was presented to PSC at the beginning of GMF2 development, I think it's a good idea to present it again next Monday

**Comment by gnerred** [comment] 2017-01-23 09:50
Ok... I hope that we will not have too much problems with that.. And for the iOS problems identified on Browserstack ?

**Comment by sbrunner** [comment] 2017-01-23 12:13
I don't think that we will support the ios 6 ...
For the others I suspect that's related to #2226?

**Comment by gnerred** [comment] 2017-01-23 12:22
Yes it is clear for iOS 6, but the problem is the same on iOS 6, 9 or 10. Not sure the problem is related to  #2226, because the application does not work even if accessed with the base URL without parameters.

**Comment by sbrunner** [comment] 2017-01-23 13:55
Now on http://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/mobile/ (with the new patch) it seem working :-)

**Comment by gnerred** [comment] 2017-01-23 14:20
Okay thanks ! Any idea of the delay for the next RC ?

**Comment by sbrunner** [comment] 2017-01-23 14:29
It should be this week :-)

**Comment by gnerred** [comment] 2017-01-23 14:29
Coool :O)

**Comment by sbrunner** [comment] 2017-01-30 15:17
@gnerred can we close it?

**Comment by gnerred** [comment] 2017-01-31 07:01
We had a discussion about it at PSC, and the conclusion was that C2C had to investigate about native Android browser. But we forgot to discuss the financial part...

**Comment by sbrunner** [comment] 2017-01-31 08:33
OK :-), thanks for the response ;-)

**Comment by ger-benjamin** [comment] 2017-02-08 14:07
@gnerred witch 'internet browser' application version do you have?

You can find it in settings->general -> application manager -> all -> internet

**Comment by gnerred** [comment] 2017-02-09 06:54
Version is 4.4.2-N5110XXDNF1

**Comment by ger-benjamin** [comment] 2017-02-09 07:42
It's look like the android version (http://androidromupdate.com/install-n5110xxdnf1-galaxy-note-8-0-n5110-official-4-4-2-kitkat-firmware-root-guide/), not the 'internet' version. I'm right ?

**Comment by gnerred** [comment] 2017-02-09 08:12
It is the version given in "general -> application manager -> all -> internet" ...  not surprising that it is the same as Android version, as browser is native to OS...

**Comment by ger-benjamin** [comment] 2017-02-09 08:31
Ok, I'll investigate. I've asked because the version number of the android on our tablet is separated of this its internet application

**Comment by sbrunner** [comment] 2017-04-03 09:28
Replaced by #2431

**Closed by sbrunner** 2017-04-03 09:28 UTC
Labels: Layout, Ready
