### ISSUE TITLE
Line of height profile jumps when zooming

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#1695] opened 2016-08-15 05:26 UTC
In the desktop application, after drawing a height profile and then zooming in at one zoom point the line jumps or disappears. An example is given in the two images below where only the zoom level is changed form image 1 to image 2.
![zoom1](https://cloud.githubusercontent.com/assets/1460598/17656299/ba9493d8-62b8-11e6-83df-25061fdda88c.png)
![zoom2](https://cloud.githubusercontent.com/assets/1460598/17656300/bcec80c8-62b8-11e6-9d72-70913296df2c.png)

This is observed in Firefox as well as Chrome

**Comment by ger-benjamin** [comment] 2016-08-15 08:44
Mhh I can't reproduce.

 - I draw a (profile) line
 - Zoom in (or out, one or multiple time)

And the line is always there and profile work well.

Tested on localhost and Github page (but not on the demo), with ~chrome and firefox.

Did I miss something ?

**Comment by marionb** [comment] 2016-08-15 10:26
The issue seems to appear somehow randomly (not on all computers). Perhaps it is linked to something observed in the following OL3 example http://openlayers.org/en/v3.2.1/examples/draw-and-modify-features.html. Drawing a LineString on the largest zoom level and then when zooming in at one point the line disappears

@fredj do you have information if this is a known issue in OL3?

**Comment by fredj** [comment] 2016-08-15 10:34
@marionb I can not reproduce the issue in the ol3 example. We need to check this together

**Comment by fredj** [comment] 2016-08-17 12:35
I can reproduce the issue with chrome:
 - http://openlayers.org/en/master/examples/draw-features.html
 - draw a line
 - zoom into the line
 - at a certain zoom level, the line disappear

**Comment by fredj** [comment] 2016-08-17 13:56
We have two issues here:
 1. the line disappear is the zoom is too important 
 2. the line is distorted in certain condition

1, this is caused by the browser itself is the coordinates are too large, for example:
```
var canvas = document.getElementById('canvas');
var ctx = canvas.getContext('2d');

ctx.moveTo(60, -2150000000);
ctx.lineTo(60, 2140000000);
ctx.stroke();
```
no line is drawn.

2. not able to reproduce; it's only reproductible on @marionb laptop :-(

**Comment by ybolognini** [comment] 2016-08-18 14:26
Moving to backlog as it is an OL problem

**Comment by sbrunner** [comment] 2017-02-10 13:50
Isn't it fixed?

**Closed** 2017-04-03 09:46 UTC
Labels: Backlog, Profiles
