### ISSUE TITLE
All groups are deleted after moving a group

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/ngeo#1744] opened 2016-08-25 07:09 UTC
To reproduce:
- OSM theme on "desktop" example
- Keeping mouse button down, start to move top group
- Keeping mouse button down, move the group down and up a little
- Move the group back to top place, release mouse button
- Click on "remove" button, all groups are deleted!

**Comment by ger-benjamin** [comment] 2016-08-25 13:00
To reproduce, you just have to select one top group, move it under another, place it anywhere, then delete it. All elements at is bottom will be deleted.

I think this arrives because we manipulate DOM in a ng-repeat. But I can't guarantee that.
If that's true, we can reproduce that on every ng-repeat with a move and delete function. We should do some tests.

**Comment by ger-benjamin** [comment] 2016-08-25 16:26
Yep, I can reproduce this error without the layertree. So that's come from ngeo-sortable or from AngularJS.

See a simple example here: https://ger-benjamin.github.io/ngeo/repeatError/examples/contribs/gmf/repeaterror.html

Code here (js): https://github.com/ger-benjamin/ngeo/blob/repeatError/contribs/gmf/examples/repeaterror.js
And there (html): https://github.com/ger-benjamin/ngeo/blob/repeatError/contribs/gmf/examples/repeaterror.html

**Comment by ger-benjamin** [comment] 2016-08-29 06:39
> So that's come from ngeo-sortable or from AngularJS.

Or from both... That because of how works angularJS and how we move the DOM That's the normal state:

![selection_066](https://cloud.githubusercontent.com/assets/1792111/18042791/c19b2c58-6dc3-11e6-9946-484e0e6c4071.png)

And that's after we have moved the DOM:

![selection_067](https://cloud.githubusercontent.com/assets/1792111/18042806/e1eb2710-6dc3-11e6-801f-8a46b60f8a70.png)
 
Only the comment `<!-- end ngRepeat: item in ctrl.items -->` has moved but that's the problem with AngularJS. We need to move it as well...

**Comment by sbrunner** [comment] 2016-08-29 06:53
I love angular ...

**Comment by ger-benjamin** [comment] 2016-09-07 11:39
Ok... I try a lot of things but I can't to solve the problem with ngeo-sortable...

The only solution that I found is to use angular-ui-sortable instead.
This lib is a little bit more complex and heavy that our directive but do the same things and handle this issue: https://github.com/angular-ui/ui-sortable/blob/master/src/sortable.js#L335-L339

I try to manage this issue with the same idea that in angular-ui-sortable (save the state of the dom element then restore it if nothing has really moved) but i fail... I can't do any actionn on the elements after "restoring the DOM" perhaps because ngeo-sortable use goog and goog use goog uid..?

What should I do ?
Asking for help or implement angular-ui + sortable (from jquery-ui) and redo a few css ?

**Comment by pgiraud** [comment] 2016-09-13 12:44
Note: this issue is not completely fixed. There are still issues with reordering that should be fixed with the layertree refactoring.

**Comment by sbrunner** [comment] 2016-10-05 08:21
Fixed with Layertree refactoring

**Comment by pgiraud** [comment] 2016-10-05 08:24
This is unfortunately not completely fixed.

**Comment by sbrunner** [comment] 2016-10-05 08:49
@pgiraud Can you provide a test case?

**Comment by pgiraud** [comment] 2016-10-05 09:52
![gmf_reorder_delete 2](https://cloud.githubusercontent.com/assets/319774/19108702/186a5a72-8af2-11e6-8aae-e9bdba2bf2cc.gif)

**Comment by sbrunner** [comment] 2016-10-05 09:53
Merci :-)

**Closed** 2016-11-03 13:08 UTC
Labels: Data, Ongoing
