### ISSUE TITLE
CSS - Subgroups must be aligned with others layers in layertree

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/ngeo#845] opened 2016-03-08 15:23 UTC
- Open: https://geomapfish-demo.camptocamp.net/2.0/wsgi/mobile/theme/OSM?lang=en&baselayer_ref=map
 - In the layertree, in the theme "OSM", the group "Layers" has a (new) subgroup "Restaurants"  but this subgroup can't be identified as such because of the css.

**Comment by pgiraud** [comment] 2016-03-16 09:10
Fixed via #884.

**Comment by pgiraud** [comment] 2016-03-24 10:03
It looks like the issue is still valid.
Restaurants is still aligned with its parent group.
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/

**Comment by olivierSemet** [comment] 2016-03-29 12:23
@pgiraud I removed one "ul" selector in the CSS rules to affect all ul element in a treenode. See the screenshot as example:
<img width="297" alt="capture d ecran 2016-03-29 a 14 22 00" src="https://cloud.githubusercontent.com/assets/8366681/14107657/cea20d9a-f5b9-11e5-9131-016d4f862800.png">

**Closed** 2016-03-29 14:39 UTC
Labels: Layout, Ready
