### ISSUE TITLE
Desktop app - features list don't appear

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1145] opened 2016-05-09 13:04 UTC
In the desktop app, when features are already drawn on the map but none is selected, there should be a list of features in the panel along with "export" and "delete all" links.
The panel is currently empty.

Note: this works as expected in the draw feature example.

![screenshot from 2016-05-09 15 03 23](https://cloud.githubusercontent.com/assets/319774/15113909/569ac716-15f7-11e6-96ef-a26ebe50dffc.png)

**Comment by adube** [comment] 2016-05-09 13:11
This PR #1121 may fix this issue.

**Comment by pgiraud** [comment] 2016-05-09 13:17
I just gave it a try. It seem to fix the list issue. Then, however, the styling editor don't show up any more.

**Comment by adube** [comment] 2016-05-09 13:31
Okay.  Just an FYI, I couldn't test in the `desktop` app because of the issue that will be fixed in #1121, so I hadn't completed the integration to it.  Once that's done, I'll be able to complete it.

**Comment by fredj** [comment] 2016-05-10 07:29
The issue can be reproduced in [desktop_alt](https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/) but it works in debug mode. An `@export` is probably missing somewhere

**Comment by fredj** [comment] 2016-05-10 10:14
`ol.Collection#getLength()` and `ol.Collection.getArray()` are not exported

**Closed** 2016-05-10 11:29 UTC
Labels: Measures, Ongoing
