### ISSUE TITLE
goBtnGroup directive - write tests

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#36] opened 2014-07-11 11:54 UTC
Write test for `goBtnGroup` and `goBtn` directives

**Comment by elemoine** [comment] 2015-01-30 17:07
The problem is beyond the `goBtnGroup` and `goBtn` directives. We have tests for the ngeo services, but not for the ngeo directives. We need to be brave and address this sooner rather than later.

**Comment by ybolognini** [comment] 2016-04-28 09:54
Can we close it?

**Comment by sbrunner** [comment] 2016-08-15 10:20
No response => close...

**Closed by sbrunner** 2016-08-15 10:20 UTC
