### ISSUE TITLE
Print-Window : Negative values in Orientation-Field

### ISSUE THREAD

**Issue by svareg** [camptocamp/ngeo#3755] opened 2018-04-12 12:58 UTC
In the Print-Window, we can configure the orientation of the map for printing. There is a slider and a number-field. But we cannot manually set negative numbers in the number-field, cause only numbers are allowed. So when we try to insert a value that begins with the char "-", the field will remain unchanged.
(Actually we can add the char "-" before the orientation value, but not replace the whole field with "-" alone)

This can be reproduced here : https://geomapfish-demo.camptocamp.net/2.2/

To correct this, I wanted to activate the allowInvalid option on the input.
But because of issues with HTML5 constraint validation, we cannot use input[type=number] with allowInvalid.  See: https://docs.angularjs.org/api/ng/input/input%5Bnumber%5D

I think a text-input should be used here, so that the character "-" will be allowed.

If further information is needed please see https://github.com/camptocamp/baselstadt_mapbs/commit/5d65f61fe3b6897ad6a3b78afc39710f72b87d6a

**Comment by ger-benjamin** [comment] 2018-04-12 14:36
Hello,
Which browser do you use ? (browser an version).
(I can't reproduce it with my chromium.)

**Comment by svareg** [comment] 2018-04-12 14:49
Hello Benjamin,

Can be reproduced with Firefox 52.0.1, IE 11.0.9600.18952 and Chrome 63.0.3239.84

To reproduce it you just have to select the whole text in the text-box (default there is only a 0), and try to replace it with "-". 
![2018-04-12 16_47_02-desktop-applikation](https://user-images.githubusercontent.com/36037102/38684987-37ae31a4-3e71-11e8-905c-e6e8a2919fa5.png)


I think this doesn't work, cause '-' is not a number and the validation fails.

Hope this helps.

**Comment by fredj** [comment] 2018-05-16 07:09
fixed with #3802

**Closed by fredj** 2018-05-16 07:09 UTC
