### ISSUE TITLE
Geolocation error on Safari

### ISSUE THREAD

**Issue by marionb** [camptocamp/ngeo#2197] opened 2017-01-12 14:06 UTC
Project:

* GitHub URL: https://github.com/camptocamp/ngeo
* GeoMapFish version: master

Permalink directly where we can reproduce the issue:
- https://camptocamp.github.io/ngeo/2.1/examples/contribs/gmf/apps/mobile

Steps to reproduce the issue:

1. Clicking on Geolocation button (and sharing location) pans to your location
2. A red dot + blue disk can be found at your location
3. Wait for a while

Result:
- After some time the following error appears
`The operation couldn't be competed. (kCLErrorDomain 0.)`
- The geolocation is turned off and the red dot + blue disk disappears
- It is possible to turn the Geolocation back on

![geolocation](https://cloud.githubusercontent.com/assets/1460598/21892439/2ddf206c-d8d7-11e6-9991-fc23893208ee.png)

Expected result:
- The error does not appear and the Geolocation stays on until it is manually turned off.

The issue concern the following environment:

* Safari iPad 3
* Safari iPod 5 

The following environment is working as expected:

* Chrome Samsung Galaxy Tab4

**Comment by fredj** [comment] 2017-01-12 14:09
Did you test on browserstack.com or on a real device ?

**Comment by marionb** [comment] 2017-01-12 14:10
on the real device

**Comment by ger-benjamin** [comment] 2017-01-23 16:13
I can't reproduce :-/

I've searched and the `kCLErrorDomain 0` error seems to be the "unknow error" of IOS when the device can't find a location.

I suspect a device problem during the test and not an error in our code.

**Comment by fredj** [comment] 2017-10-02 14:31
was working during the 2.2 tests, closing

**Closed by fredj** 2017-10-02 14:31 UTC
Labels: Backlog, Map
