### ISSUE TITLE
Use of is_password_changed

### ISSUE THREAD

**Issue by svaabs** [camptocamp/ngeo#3278] opened 2017-12-15 10:15 UTC
In cgxp the purpose of the attribute _is_password_changed_ was to show a message and force the user to change his password if the value was set to false. How is this done in ngeo or is there no more use of this feature?

**Comment by ger-benjamin** [comment] 2017-12-21 08:27
It seems that this value exist in ngeo but is not used. So it looks like there is no implemented mechanism to force the user to change his password for now.

**Comment by ybolognini** [comment] 2018-01-08 10:31
To do

**Comment by ger-benjamin** [comment] 2018-01-09 13:36
I've added a `gmf-authentication-force-password-change` attribute. See #3346

**Comment by svaabs** [comment] 2018-02-02 13:30
Thanks for working on this. I had the chance to implement it on our gmf222-branch and unhappily it does not work as expected.
When I login with a user that has _is_password_changed_ set to false, I don't get any message (but I do expect one). As soon as the page is fully refreshed, the message appears.
Can you reproduce this on demo?

**Comment by ger-benjamin** [comment] 2018-02-05 09:27
:-/ Sadly I can reproduce the issue, I'll fix it soon

**Comment by ger-benjamin** [comment] 2018-02-08 09:43
Fixed with #3484

**Closed by ger-benjamin** 2018-02-08 09:43 UTC
Labels: Authentication, Ongoing
