### ISSUE TITLE
2.2 - Interpret HTML tags in result window

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/ngeo#3243] opened 2017-12-11 11:10 UTC
In the result grid, HTML tags are interpreted, i.e. `m<sup>2</sup>` results in:

![image](https://user-images.githubusercontent.com/1681332/33828356-0fcc0216-de6c-11e7-9fad-06c091deafe5.png)

But this is not the case in the result window:

![image](https://user-images.githubusercontent.com/1681332/33828386-33d91d6a-de6c-11e7-9470-2abaf9b2b3a3.png)

And it should also be the case IMHO

**Comment by fredj** [comment] 2017-12-11 11:30
duplicate of #2932 ?

**Comment by kalbermattenm** [comment] 2017-12-11 12:30
Oups... It looks like...

**Closed** 2017-12-11 15:46 UTC
Labels: Ongoing
